### ISSUE TITLE
Possibilité d'ajouter un assoifé en tant qu'organisateur de tournée

### ISSUE THREAD

**Issue by Heartbroken-Git** [reveliant/mabinouze#1]
Petite *feature request* après un premier test "terrain" : la possibilité d'ajouter soi-même, en tant qu'organisateur de la tournée, un assoiffé qui aurait fait parvenir sa commande à l'organisateur par un canal auxilliaire, par exemple un courriel.

L'assoiffé ajouté pourrait être "factice" en ce sens qu'il n'aurait pas de mot de passe /de capacité à se connecter et modifier lui-même la commande. Mais l'objectif serait d'avoir un rendu identique (Prénom + commande) en terme de lecture au moment du passage devant le bar pour passer la commande et aussi de bénéficier de la concaténation des commandes identiques.

En effet lors du test quelques irréductibles et étourdis ne sont pas passés par l'outil. La solution de contournement choisie pour éviter de se retrouver à cumuler commande numérique et papiers a été d'ajouter les commandes des intéressés en sus de celle de l'organisateur. Sauf que pour noter aussi qui avait commandé quoi une note était ajouté à chaque commande. De fait une commande identique n'avait pas la même chaine de caractère et avait donc plusieurs entrées.

**Comment by reveliant** [comment]
C'est prévu dans la roadmap, avec l'ajout d'un mode "Édition des commandes" sur la page de détail, qui affichera les champs de saisie de nouvelle consommation pour chaque participant, ainsi qu'un champ nom et mot de passe pour un nouveau participant.

Lorsque le mode sera désactivé (statut par défaut), seul le nom et les consommations des participants seront affichés, de manière plus lisible.
