### ISSUE TITLE
Commandes bloquées

### ISSUE THREAD

**Issue by Heartbroken-Git** [reveliant/mabinouze#5]
Je constate ce matin que les commandes du pot de la semaine passées sont toujours présentes sur la tournée "réservée". Elles n'ont apparemment pas été nettoyée automatiquement. 

Je vais pour les supprimer manuellement depuis l'interface de détail de la commande et ça ne marche pas non plus. 

J'ai une erreur 500 dans la console quand je tente de faire des actions sur les commandes.

**Comment by reveliant** [comment]
Problème non lié au code source mais à l'occupation de disque de l'instance publique.
